### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [cookiehub-com/gtm-template-cookiehub#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1)encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "code" when generating the url
let url = (production ? 'https://cookiehub.net/c2/' : 'https://dash.cookiehub.com/dev/') + code + '.js';

**Comment by astthorip** [comment]
@praveena-pappu encodeUriComponent has been implemented
