### ISSUE TITLE
Missing default consent wait_for_update

### ISSUE THREAD

**Issue by philpott** [cookiehub-com/gtm-template-cookiehub#3]
https://github.com/cookiehub-com/gtm-template-cookiehub/blob/b7bd1d09297d90ab7f1e63e6b7bd2d3d322a9f01/template.tpl#L562

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by astthorip** [comment]
@philpott wait_for_update has been added to the default consent state

**Comment by philpott** [comment]
Thanks!
